"""add_failure_reason_to_playbook

Revision ID: 3a218dd6fb62
Revises: 3c0b9d1e4f2a
Create Date: 2026-04-01 17:58:15.484121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a218dd6fb62'
down_revision: Union[str, Sequence[str], None] = '3c0b9d1e4f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failure_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')

    # ### end Alembic commands ###
