"""rename market_data_fields to context

Revision ID: 3a7906b95505
Revises: 645485dd03f3
Create Date: 2026-02-27 20:37:19.124324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a7906b95505'
down_revision: Union[str, Sequence[str], None] = '645485dd03f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('playbooks') as batch_op:
        batch_op.alter_column('market_data_fields', new_column_name='context')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playbooks', 'context', new_column_name='market_data_fields')
    # ### end Alembic commands ###
