"""create_condition_and_edge_tables

Revision ID: 3e6e9634ffdc
Revises: e2f39830f0fe
Create Date: 2026-02-27 17:24:38.223112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e6e9634ffdc'
down_revision: Union[str, Sequence[str], None] = 'e2f39830f0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comparator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conditions_id'), 'conditions', ['id'], unique=False)
    op.create_index(op.f('ix_conditions_rule_id'), 'conditions', ['rule_id'], unique=False)
    op.create_table('condition_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('parent_condition_id', sa.Uuid(), nullable=False),
    sa.Column('child_condition_id', sa.Uuid(), nullable=False),
    sa.Column('logical_operator', sa.Enum('AND', 'OR', name='logical_operator_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['parent_condition_id'], ['conditions.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_edges_child_condition_id'), 'condition_edges', ['child_condition_id'], unique=False)
    op.create_index(op.f('ix_condition_edges_id'), 'condition_edges', ['id'], unique=False)
    op.create_index(op.f('ix_condition_edges_parent_condition_id'), 'condition_edges', ['parent_condition_id'], unique=False)
    op.create_index(op.f('ix_condition_edges_rule_id'), 'condition_edges', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condition_edges_rule_id'), table_name='condition_edges')
    op.drop_index(op.f('ix_condition_edges_parent_condition_id'), table_name='condition_edges')
    op.drop_index(op.f('ix_condition_edges_id'), table_name='condition_edges')
    op.drop_index(op.f('ix_condition_edges_child_condition_id'), table_name='condition_edges')
    op.drop_table('condition_edges')
    op.drop_index(op.f('ix_conditions_rule_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_id'), table_name='conditions')
    op.drop_table('conditions')
    # ### end Alembic commands ###
