"""setup_canonical_rules_table

Revision ID: 4cfcb5937445
Revises: 2dd012ae1044
Create Date: 2026-02-24 16:41:58.737885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4cfcb5937445'
down_revision: Union[str, Sequence[str], None] = '2dd012ae1044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('playbook_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=True),
    sa.Column('rule_json', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('useractionrun')
    op.drop_table('rule')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('rule_nl', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('useractionrun',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(), nullable=False),
    sa.Column('raw_input_text', sa.TEXT(), nullable=True),
    sa.Column('rule_output_json', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rules')
    # ### end Alembic commands ###
