"""add market_data_fields to playbook

Revision ID: 645485dd03f3
Revises: c5224aa0a631
Create Date: 2026-02-27 20:22:55.244969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '645485dd03f3'
down_revision: Union[str, Sequence[str], None] = 'c5224aa0a631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playbooks', sa.Column('market_data_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbooks', 'market_data_fields')
    # ### end Alembic commands ###
