"""add user role field

Revision ID: 6bf7f68619f9
Revises: 4b6f5f1f8a2e
Create Date: 2026-04-03 16:29:40.993427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bf7f68619f9'
down_revision: Union[str, Sequence[str], None] = '4b6f5f1f8a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type manually for PostgreSQL
    user_role_enum = sa.Enum('standard', 'admin', name='user_role_enum')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', user_role_enum, server_default='standard', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
