"""add_cascading_deletes

Revision ID: 88441d70a650
Revises: 5581b1f8cc2f
Create Date: 2026-04-09 16:24:06.255896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88441d70a650'
down_revision: Union[str, Sequence[str], None] = '5581b1f8cc2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condition_edges', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('condition_edges_child_condition_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('condition_edges_rule_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('condition_edges_parent_condition_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'conditions', ['parent_condition_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'conditions', ['child_condition_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'rules', ['rule_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conditions_rule_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'rules', ['rule_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('playbooks_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rules_playbook_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'playbooks', ['playbook_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('session_events_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sessions', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sessions_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('sessions_playbook_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'playbooks', ['playbook_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sessions_playbook_id_fkey'), 'playbooks', ['playbook_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('sessions_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('session_events_session_id_fkey'), 'sessions', ['session_id'], ['id'])

    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rules_playbook_id_fkey'), 'playbooks', ['playbook_id'], ['id'])

    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('playbooks_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conditions_rule_id_fkey'), 'rules', ['rule_id'], ['id'])

    with op.batch_alter_table('condition_edges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('condition_edges_parent_condition_id_fkey'), 'conditions', ['parent_condition_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('condition_edges_rule_id_fkey'), 'rules', ['rule_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('condition_edges_child_condition_id_fkey'), 'conditions', ['child_condition_id'], ['id'])

    # ### end Alembic commands ###
