"""add_is_active_flags

Revision ID: 9a649b22657e
Revises: 3e6e9634ffdc
Create Date: 2026-02-27 17:44:19.119928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a649b22657e'
down_revision: Union[str, Sequence[str], None] = '3e6e9634ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('playbooks', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('rules', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'is_active')
    op.drop_column('playbooks', 'is_active')
    op.drop_column('conditions', 'is_active')
    # ### end Alembic commands ###
