"""add chat_history and INCOMPLETE status

Revision ID: ab058548b6a2
Revises: 2973e426a800
Create Date: 2026-04-09 09:30:09.280583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab058548b6a2'
down_revision: Union[str, Sequence[str], None] = '2973e426a800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE generation_status_enum ADD VALUE IF NOT EXISTS 'INCOMPLETE'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('chat_history')

    # ### end Alembic commands ###
