"""add original_nl_input to playbook

Revision ID: c5224aa0a631
Revises: 9a649b22657e
Create Date: 2026-02-27 19:41:54.929153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5224aa0a631'
down_revision: Union[str, Sequence[str], None] = '9a649b22657e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use batch_alter_table for SQLite compatibility
    with op.batch_alter_table('playbooks') as batch_op:
        # 1. Add the column as nullable first to safely handle existing data
        batch_op.add_column(sa.Column('original_nl_input', sa.Text(), nullable=True))
    
    # 2. Backfill existing entries with a safe default (empty string)
    op.execute("UPDATE playbooks SET original_nl_input = '' WHERE original_nl_input IS NULL")
    
    # 3. Alter the column to satisfy the required constraint
    with op.batch_alter_table('playbooks') as batch_op:
        batch_op.alter_column('original_nl_input', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playbooks', 'original_nl_input')
    # ### end Alembic commands ###
