"""refactor_rule_to_grouping

Revision ID: e2f39830f0fe
Revises: e7727b961a75
Create Date: 2026-02-27 17:10:56.805864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f39830f0fe'
down_revision: Union[str, Sequence[str], None] = 'e7727b961a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('rules', 'rule_text')
    op.drop_column('rules', 'status')
    op.drop_column('rules', 'rule_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('rule_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('rules', sa.Column('rule_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('rules', 'name')
    # ### end Alembic commands ###
